### ISSUE TITLE
use `notarytool` instead of `altool`

### ISSUE THREAD

**Issue by tbussmann** [jo-tools/xojo2dmg#11]
First, let me thank you for providing this incredibly useful script!

Apple [deprecated](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow/notarizing_apps_when_developing_with_xcode_12_and_earlier?language=objc) `altool` and is [replacing](https://developer.apple.com/videos/play/wwdc2021/10261/) it with `notarytool`. The API used by `altool` will be [disabled in Autumn 2023](
https://developer.apple.com/videos/play/wwdc2022/10109/), so in about one year. It would be great to see this script updated to use the [new API](https://developer.apple.com/documentation/notaryapi)'s client [`notarytool`](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow) in time for this change. On the other hand, sticking with `altool` as long as possible allows to maintain compatibility with Xcode 12 and earlier, which also has its advantages.

**Comment by jo-tools** [comment]
> First, let me thank you for providing this incredibly useful script!

You're welcome. Glad to hear that it's useful to others, too!

> It would be great to see this script updated to use the [new API](https://developer.apple.com/documentation/notaryapi)'s client [notarytool](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow) in time

Thanks for this information and the links.
I'll update it *(soon)*.

> On the other hand, sticking with altool as long as possible allows to maintain compatibility with Xcode 12 and earlier, which also has its advantages.

I don't intend to keep compatibility with Xcode < 13 when switching to ```notarytool```.
If Xcode < 13 is required, one can always use a previous *(as of today: current)* version of Xojo2DMG.
